### PR TITLE
JSON now used for Sim statefile backends

### PR DESCRIPTION
**Pull request by dotsdl**
This PR makes the necessary changes needed for `mdsynthesis` to accommodate changes in upstream `datreant` in [this PR](https://github.com/datreant/datreant/pull/33). The PyTables backend for storing `Sim` state information has been replaced with a JSON backend. No API changes have been made.

A [script](https://github.com/datreant/pytables-to-json/blob/master/pytables-to-json.py) for creating JSON state files from the now-deprecated HDF5 state files is ready for use.

### CODE REVIEW

**Comment by kain88-de** [comment]
FYI I will start looking at this once the upstream changes in datreant go live (you make a new release)

**Comment by dotsdl** [comment]
May I go ahead and merge this? I did a major refactor of `Limb`s inside MDSynthesis in line with the same refactor in upstream `datreant`, that work ([`limbrefactor` branch](https://github.com/datreant/MDSynthesis/tree/exp-json_only)) building upon these commits. The new form of things is here to stay, and everything currently in `datreant.core` and `datreant.data`'s development branch will directly benefit MDS.

In the future, following release, MDS releases will definitely lag behind `datreant`. But for now I think being synchronized drives development.

**Comment by kain88-de** [comment]
If you are ok with that I'm fine. I'm sorry I don't really have time to look over these things currently

**Comment by dotsdl** [comment]
@kain88-de not a problem. I've been on a tear so it's a giant PR anyway.

**Pull request merged**
